data:
  train_urls:
      - "gs://levanter-data/audio-data/sharded-shuf/train.shard-{0..31}.txt"
  validation_urls:
      - "gs://levanter-data/audio-data/valid-small.txt"
  cache_dir: "gs://levanter-data/audio-data/cache-shuf/"
  tokenizer: "passthrough"
  plaintext: True
  vocab_size: 1127
  enforce_eos: False
model:
  type: llama
initialize_from_hf: true
use_hf_model_config: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "audio", "llama2"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 1
  per_device_eval_parallelism: 1
  num_train_steps: 10000
  train_batch_size: 64
  steps_per_eval: 500

  checkpointer:
    base_path: gs://levanter-data/audio-checkpoints/
    save_interval: 30m
optimizer:
  learning_rate: 1.2e-4
  weight_decay: 0.0
