data:
  train_urls:
      - "dkakdkad"
  validation_urls:
      - "lamdaklsd"
  cache_dir: "/files/lakhmidi-data/cache"
  tokenizer: passthrough
model:
  hidden_dim: 1536
  num_heads: 24
  num_layers: 48
  seq_len: 2048
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  mp: p=f32,c=bfloat16
  learning_rate: 1E-4
  weight_decay: 0.1
  model_axis_size: 1
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 8

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
  # ZERO-3
  parameter_axis_resources:
    embed: "data"
