data:
  train_urls:
      - "gs://levanter-eu/lakh-data-inter-16384/train.txt"
  validation_urls:
      - "gs://levanter-eu/lakh-data-inter-16384/valid.txt"
  cache_dir: "gs://levanter-eu/lakh-data-inter-16384/cache/"
  tokenizer: "passthrough"
  plaintext: True
  enforce_eos: False
model:
  hidden_dim: 1024
  num_heads: 16
  num_layers: 24
  seq_len: 16384
  scale_attn_by_inverse_layer_idx: true
  embed_pdrop: 0.1
  resid_pdrop: 0.1
  gradient_checkpointing: true
trainer:
  mp: p=f32,c=bfloat16
  learning_rate: 1E-5
  weight_decay: 0.1
  model_axis_size: 2
  per_device_parallelism: 1
  num_train_steps: 15000
  load_checkpoint_path: "gs://levanter-eu/lakh-checkpoints/young-brook-165/step-100000"
  train_batch_size: 32

  checkpointer:
    base_path: gs://levanter-eu/lakh-checkpoints/
    save_interval: 30m

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
  parameter_axis_resources:
    embed: "data"
