data:
  train_urls:
      - "/files/lakhmidi-data/train.txt"
  validation_urls:
      - "/files/lakhmidi-data/test.txt"
  cache_dir: "/files/lakhmidi-data/cache/"
  tokenizer: "passthrough"
  plaintext: True
  enforce_eos: False
model:
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 1024
  scale_attn_by_inverse_layer_idx: true
trainer:
  mp: p=f32,c=bfloat16
  learning_rate: 6E-4
  weight_decay: 0.1
  model_axis_size: 1
  per_device_train_batch_size: 4
  steps_per_save: 10000

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
