data:
  train_urls:
      - "/nlp/scr/jthickstun/anticipation/datasets/arrival/train.txt"
  validation_urls:
      - "/nlp/scr/jthickstun/anticipation/datasets/arrival/valid-small.txt"
  cache_dir: "/nlp/scr/kathli/cache/"
  tokenizer: "passthrough"
  plaintext: True
  enforce_eos: False
model:
  hidden_dim: 384
  num_heads: 12
  num_layers: 12
trainer:
  mp: f32
  num_train_steps: 20000

  checkpointer:
    save_interval: 30m

  per_device_eval_parallelism: 2
  per_device_parallelism: 2
  train_batch_size: 32
  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
